### ISSUE TITLE
markdown is ready

### ISSUE THREAD

**Issue by bernhardeymann** [UniLuFS2020-ReplicationSeminar/CE2_Bernhard_Josia_Nico#6]
hi guys,

i completed the markdown file as far as i was able to. josia wanted to add something as soon as he got the additional keys. i did not execute any code in order to not use the query limit. will you be able Josia to complete the analysis on your own, josia, and then save the markdown as an html? i might be able to contribute more on friday if necessary.

thanks  both of your great work!

bernhard

**Comment by JDSchramm** [comment]
Thank Bernhard, i changed the code so the API requests dont go out if the data is already stored, so you can run it aswell now. 
I did some changes on the report and rendered the html, so we are all set.

Was great working with you two!
Josia

**Comment by bernhardeymann** [comment]
Looks perfect, thanks :)
